<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>ul_51025</name>
   <tag></tag>
   <elementGuidId>dab0f5e5-d9f9-4211-b4b6-37635b9ca3ae</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#mui-30</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//ul[@id='mui-30']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>ul</value>
      <webElementGuid>b358c3bf-8f25-4e09-b08f-6a298ba04da0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>MuiList-root MuiList-padding MuiMenu-list css-r8u8y9</value>
      <webElementGuid>476249db-51ac-462b-83a1-8bf22c609d11</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>role</name>
      <type>Main</type>
      <value>listbox</value>
      <webElementGuid>a755478e-f5b5-4c05-a7d2-fa4dd9e684fd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tabindex</name>
      <type>Main</type>
      <value>-1</value>
      <webElementGuid>bc7a8521-94ba-4d1b-9ac7-d09412737727</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-labelledby</name>
      <type>Main</type>
      <value>mui-32</value>
      <webElementGuid>9464394d-5cf4-4a41-bf52-fa3a65de3039</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>mui-30</value>
      <webElementGuid>3b96c33a-2f3e-433a-8422-61e8197b9ce9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>51025</value>
      <webElementGuid>ec822e4b-a734-41bc-8c00-c9a4f75375a7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;mui-30&quot;)</value>
      <webElementGuid>474cf5e7-8bc5-4edf-bfc0-6fff1b2788f5</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//ul[@id='mui-30']</value>
      <webElementGuid>74173a58-3c6f-4875-b17d-972437d45b0a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='menu-']/div[3]/ul</value>
      <webElementGuid>c1591da6-ac15-45fc-9329-3d513f63fba3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Delete'])[10]/following::ul[1]</value>
      <webElementGuid>4090ba2e-4dea-45a8-a6b3-484fe1d16cfe</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Edit'])[10]/following::ul[1]</value>
      <webElementGuid>834d3282-0109-4492-9db9-e22dead88c24</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[13]/div[3]/ul</value>
      <webElementGuid>2e848d33-f341-44cd-b6ad-938c76ef0e66</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//ul[@id = 'mui-30' and (text() = '51025' or . = '51025')]</value>
      <webElementGuid>8b9833bb-0a5f-4c14-b776-fe2a3714bc8e</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
