<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>li_3D</name>
   <tag></tag>
   <elementGuidId>9d267f10-ef5d-449b-bdf5-625bfef6515d</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#job_departement-option-0</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//li[@id='job_departement-option-0']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>li</value>
      <webElementGuid>7dc6b479-2068-4cab-86b6-1c14a0d3058a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>MuiButtonBase-root MuiMenuItem-root MuiMenuItem-gutters MuiAutocomplete-option css-1fh5cnl Mui-focused</value>
      <webElementGuid>1aecee4d-b98c-40d4-8008-493222763b57</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tabindex</name>
      <type>Main</type>
      <value>-1</value>
      <webElementGuid>cea35f2c-34ac-4319-8f64-b9442d395834</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>role</name>
      <type>Main</type>
      <value>option</value>
      <webElementGuid>121d05d3-563d-4420-acd8-02fc3267a244</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>job_departement-option-0</value>
      <webElementGuid>d1e827e7-c001-4faf-a08d-13b47d3581b7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-option-index</name>
      <type>Main</type>
      <value>0</value>
      <webElementGuid>6e392741-14aa-4099-b5f4-9b54f9908865</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-disabled</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>1aaf3eea-3553-487c-931a-468aead92315</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-selected</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>1ba080d0-36c4-4838-909c-cba9795115fd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>3D </value>
      <webElementGuid>7b2d61f4-94f6-4096-ba87-55929e22e34a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;job_departement-option-0&quot;)</value>
      <webElementGuid>1b8f9ff6-b0eb-46a1-8538-634757265f1c</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//li[@id='job_departement-option-0']</value>
      <webElementGuid>fd9f3d09-f1aa-421d-8164-0fd56022c3de</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//ul[@id='job_departement-listbox']/li</value>
      <webElementGuid>0911512b-8c75-402a-ba59-0b366d7e7d9c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Batal'])[1]/following::li[1]</value>
      <webElementGuid>3daa6f92-7ab1-464a-aacd-45faf2926480</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Tambah'])[1]/following::li[1]</value>
      <webElementGuid>5b3b2a7e-9d48-49ff-96de-1f2c17d94203</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='AFI Desk Collection'])[1]/preceding::li[1]</value>
      <webElementGuid>33fbb686-b017-4027-a430-4a203cfa3367</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Air Asia'])[1]/preceding::li[2]</value>
      <webElementGuid>6775e873-98c8-4dda-865b-ebfffd6701be</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[14]/div/ul/li</value>
      <webElementGuid>4528abb9-7216-484d-ae53-979386c42fa6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//li[@id = 'job_departement-option-0' and (text() = '3D ' or . = '3D ')]</value>
      <webElementGuid>8fe7ca13-c909-4b98-ae50-e96412e2b557</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
