<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Jumlah Bulan Kerja Sisa Cuti_carry_fo_08b2bb</name>
   <tag></tag>
   <elementGuidId>59242674-73a6-42b2-a757-ee2d417fabf1</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='carry_forward_total_month']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#carry_forward_total_month</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>b590c86f-496f-4582-91ac-16add1814801</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-invalid</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>ebdafb85-2216-445a-bdc4-ecf192cdd27e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>carry_forward_total_month</value>
      <webElementGuid>8760c41a-7a83-498c-ab38-74ccd5e0c872</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>carry_forward_total_month</value>
      <webElementGuid>1101bcdd-e48e-4e1c-ba13-e1d525554767</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Jumlah Bulan Kerja Sisa Cuti</value>
      <webElementGuid>21c6e010-674f-495c-84e4-f807a190c39b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>number</value>
      <webElementGuid>77e78d37-de61-4601-9aa0-8774b14b9a33</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>MuiInputBase-input MuiOutlinedInput-input MuiInputBase-inputSizeSmall css-1o6z5ng</value>
      <webElementGuid>776ba250-a56a-4366-bf6b-ad2f5d1d08e5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>0</value>
      <webElementGuid>5439d510-67c6-4539-8645-254ab2ad7eda</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;carry_forward_total_month&quot;)</value>
      <webElementGuid>b7845c08-f1d7-4d7f-b06a-2e375c3f4588</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='carry_forward_total_month']</value>
      <webElementGuid>2291b5d7-9b1f-4025-a974-6a5c98c2e0a1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[6]/div/div/input</value>
      <webElementGuid>2f2d6f34-53f3-4a60-8bc4-3ceef37835d5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'carry_forward_total_month' and @name = 'carry_forward_total_month' and @placeholder = 'Jumlah Bulan Kerja Sisa Cuti' and @type = 'number']</value>
      <webElementGuid>651901a2-3be5-40b7-9936-76c0aa647b59</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
