<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Eligible Pengaturan Cuti (Bulan)_elig_9860f4</name>
   <tag></tag>
   <elementGuidId>edd857ee-2078-4bab-a7a5-a122334df60b</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='eligible_leave_total_month']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#eligible_leave_total_month</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>52bd4c07-219d-4f75-8f41-02ae1dae36e5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-invalid</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>535487c7-c60a-48bc-bfb8-37ee75ea47e5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>eligible_leave_total_month</value>
      <webElementGuid>4dcb6d9a-9401-4a08-b2a6-5ac37e2d6be4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>eligible_leave_total_month</value>
      <webElementGuid>27696936-2177-40d8-9b74-8d60b3227a42</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Eligible Pengaturan Cuti</value>
      <webElementGuid>f741a539-9cd8-422e-8a87-a7925e477cc8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>number</value>
      <webElementGuid>afbfefb9-5cc6-4f49-ab04-176b5d083b3b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>MuiInputBase-input MuiOutlinedInput-input MuiInputBase-inputSizeSmall css-1o6z5ng</value>
      <webElementGuid>4e954c0f-98ee-49ae-80b1-ca9a0a26ed2a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>0</value>
      <webElementGuid>a9eea911-f984-4158-9867-e3cd5b78f9bc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;eligible_leave_total_month&quot;)</value>
      <webElementGuid>ee0bb36c-9ed6-4e09-8fdf-1b1af4a2b9b8</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='eligible_leave_total_month']</value>
      <webElementGuid>e5aae739-3cfa-4c73-a137-637b124ccbbd</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//form/div[2]/div/div/input</value>
      <webElementGuid>d52048eb-ee14-47e4-85e5-fd98ac320a8f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'eligible_leave_total_month' and @name = 'eligible_leave_total_month' and @placeholder = 'Eligible Pengaturan Cuti' and @type = 'number']</value>
      <webElementGuid>baf0c250-3a6d-4dc3-943f-c9cdf7161353</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
