<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Maksimal Sisa Cuti_max_carry_forward</name>
   <tag></tag>
   <elementGuidId>57059c6d-6dbb-4d3a-9f8c-328d2aac70ba</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='max_carry_forward']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#max_carry_forward</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>d82569e7-7a4f-4ddd-9f1f-2d4cca7592d5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-invalid</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>9976bdd5-dc43-4d05-a48f-4b75192187a3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>max_carry_forward</value>
      <webElementGuid>912e0877-4069-4fca-ba28-611ebac2e533</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>max_carry_forward</value>
      <webElementGuid>aaed24be-2620-4999-9f35-1afeaf3c2902</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Maksimal Sisa Cuti</value>
      <webElementGuid>0dbd0a03-1fdf-49cb-8d90-ca0b08e53b5d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>number</value>
      <webElementGuid>80f8d0f9-7025-4df7-861a-1d2b6ffc0a8c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>MuiInputBase-input MuiOutlinedInput-input MuiInputBase-inputSizeSmall css-1o6z5ng</value>
      <webElementGuid>a5181ed9-79af-4c77-a09c-065a3c6b188a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>0</value>
      <webElementGuid>61814111-e916-4d24-9b47-f9a7777af95d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;max_carry_forward&quot;)</value>
      <webElementGuid>e1c42fb3-4ada-4df8-ac78-3bc34d0a8f8f</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='max_carry_forward']</value>
      <webElementGuid>e65f7e73-b663-4784-a4dd-ea2ecd42f203</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[5]/div/div/input</value>
      <webElementGuid>245860ff-6c2d-4642-a4d3-7838a60fb530</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'max_carry_forward' and @name = 'max_carry_forward' and @placeholder = 'Maksimal Sisa Cuti' and @type = 'number']</value>
      <webElementGuid>e8828b88-ecd2-407f-b418-61f29d118ed4</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
