<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>ul_51025</name>
   <tag></tag>
   <elementGuidId>49910161-a361-4e1b-8eab-c16beaf416b9</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#mui-45</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//ul[@id='mui-45']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>ul</value>
      <webElementGuid>d30f0c37-7230-4d31-86e3-8988870a3e95</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>MuiList-root MuiList-padding MuiMenu-list css-r8u8y9</value>
      <webElementGuid>6d39e974-d3c5-450d-a5d1-53039b061e5e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>role</name>
      <type>Main</type>
      <value>listbox</value>
      <webElementGuid>83ff3189-d495-4fa6-93a1-37086cb97784</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tabindex</name>
      <type>Main</type>
      <value>-1</value>
      <webElementGuid>631fff49-9021-451a-9e41-bbd45b3c4c5a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-labelledby</name>
      <type>Main</type>
      <value>mui-47</value>
      <webElementGuid>83cfc6c9-88f3-4dbb-ac24-efdef99c6e10</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>mui-45</value>
      <webElementGuid>f59ca2aa-6992-4f19-a08b-2870cdd74822</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>51025</value>
      <webElementGuid>78ae6f2b-0a5c-4604-ba24-ef5578ef3439</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;mui-45&quot;)</value>
      <webElementGuid>ebc019ae-332d-4f0a-9b0b-604f8a97de69</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//ul[@id='mui-45']</value>
      <webElementGuid>34a3ff99-c21c-4a68-8b82-95f1a1388ce8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='menu-']/div[3]/ul</value>
      <webElementGuid>ee7d7b87-cf49-46da-8ee0-c0ab4e88b1bf</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Logout'])[1]/following::ul[1]</value>
      <webElementGuid>050dcf37-cbc6-4fc3-8c95-b4bbd02bd953</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Ubah Password'])[1]/following::ul[1]</value>
      <webElementGuid>3af1137d-728c-44df-a1ae-40e32035924e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/div[3]/ul</value>
      <webElementGuid>67099b98-9bd0-47d8-b51f-f3a0fe8a4b5f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//ul[@id = 'mui-45' and (text() = '51025' or . = '51025')]</value>
      <webElementGuid>6ad6bf58-c12a-4fee-b26c-07c38cf22082</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
